// Generated by gencpp from file svg_ros/EnvironmentSrv.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_ENVIRONMENTSRV_H
#define SVG_ROS_MESSAGE_ENVIRONMENTSRV_H

#include <ros/service_traits.h>


#include <svg_ros/EnvironmentSrvRequest.h>
#include <svg_ros/EnvironmentSrvResponse.h>


namespace svg_ros
{

struct EnvironmentSrv
{

typedef EnvironmentSrvRequest Request;
typedef EnvironmentSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnvironmentSrv
} // namespace svg_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svg_ros::EnvironmentSrv > {
  static const char* value()
  {
    return "caeffbf51b8bc21c7838947aa06fdc32";
  }

  static const char* value(const ::svg_ros::EnvironmentSrv&) { return value(); }
};

template<>
struct DataType< ::svg_ros::EnvironmentSrv > {
  static const char* value()
  {
    return "svg_ros/EnvironmentSrv";
  }

  static const char* value(const ::svg_ros::EnvironmentSrv&) { return value(); }
};


// service_traits::MD5Sum< ::svg_ros::EnvironmentSrvRequest> should match 
// service_traits::MD5Sum< ::svg_ros::EnvironmentSrv > 
template<>
struct MD5Sum< ::svg_ros::EnvironmentSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::EnvironmentSrv >::value();
  }
  static const char* value(const ::svg_ros::EnvironmentSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::EnvironmentSrvRequest> should match 
// service_traits::DataType< ::svg_ros::EnvironmentSrv > 
template<>
struct DataType< ::svg_ros::EnvironmentSrvRequest>
{
  static const char* value()
  {
    return DataType< ::svg_ros::EnvironmentSrv >::value();
  }
  static const char* value(const ::svg_ros::EnvironmentSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svg_ros::EnvironmentSrvResponse> should match 
// service_traits::MD5Sum< ::svg_ros::EnvironmentSrv > 
template<>
struct MD5Sum< ::svg_ros::EnvironmentSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::svg_ros::EnvironmentSrv >::value();
  }
  static const char* value(const ::svg_ros::EnvironmentSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::svg_ros::EnvironmentSrvResponse> should match 
// service_traits::DataType< ::svg_ros::EnvironmentSrv > 
template<>
struct DataType< ::svg_ros::EnvironmentSrvResponse>
{
  static const char* value()
  {
    return DataType< ::svg_ros::EnvironmentSrv >::value();
  }
  static const char* value(const ::svg_ros::EnvironmentSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVG_ROS_MESSAGE_ENVIRONMENTSRV_H
