// Generated by gencpp from file svg_ros/EnvironmentSrvResponse.msg
// DO NOT EDIT!


#ifndef SVG_ROS_MESSAGE_ENVIRONMENTSRVRESPONSE_H
#define SVG_ROS_MESSAGE_ENVIRONMENTSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace svg_ros
{
template <class ContainerAllocator>
struct EnvironmentSrvResponse_
{
  typedef EnvironmentSrvResponse_<ContainerAllocator> Type;

  EnvironmentSrvResponse_()
    : sensor(0)
    , light(0)
    , base(0)
    , invert(0)  {
    }
  EnvironmentSrvResponse_(const ContainerAllocator& _alloc)
    : sensor(0)
    , light(0)
    , base(0)
    , invert(0)  {
  (void)_alloc;
    }



   typedef int32_t _sensor_type;
  _sensor_type sensor;

   typedef int32_t _light_type;
  _light_type light;

   typedef int32_t _base_type;
  _base_type base;

   typedef int32_t _invert_type;
  _invert_type invert;




  typedef boost::shared_ptr< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EnvironmentSrvResponse_

typedef ::svg_ros::EnvironmentSrvResponse_<std::allocator<void> > EnvironmentSrvResponse;

typedef boost::shared_ptr< ::svg_ros::EnvironmentSrvResponse > EnvironmentSrvResponsePtr;
typedef boost::shared_ptr< ::svg_ros::EnvironmentSrvResponse const> EnvironmentSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace svg_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5e34c9de9177eab7ad1a82eb740ae59";
  }

  static const char* value(const ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5e34c9de9177eabULL;
  static const uint64_t static_value2 = 0x7ad1a82eb740ae59ULL;
};

template<class ContainerAllocator>
struct DataType< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "svg_ros/EnvironmentSrvResponse";
  }

  static const char* value(const ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sensor\n\
int32 light\n\
int32 base\n\
int32 invert\n\
\n\
";
  }

  static const char* value(const ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor);
      stream.next(m.light);
      stream.next(m.base);
      stream.next(m.invert);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnvironmentSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::svg_ros::EnvironmentSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "sensor: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor);
    s << indent << "light: ";
    Printer<int32_t>::stream(s, indent + "  ", v.light);
    s << indent << "base: ";
    Printer<int32_t>::stream(s, indent + "  ", v.base);
    s << indent << "invert: ";
    Printer<int32_t>::stream(s, indent + "  ", v.invert);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SVG_ROS_MESSAGE_ENVIRONMENTSRVRESPONSE_H
